In [1]:
import numpy as np

# 1D Array
arr_1d = np.array([1, 2, 3, 4])
print("1D Array:\n", arr_1d)
print("Sum (Axis 0):", np.sum(arr_1d, axis=0))  # Single axis, so sum of all elements


# 2D Array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\n2D Array:\n", arr_2d)
print("Sum along rows (Axis 0):", np.sum(arr_2d, axis=0))  # [5 7 9]
print("Sum along columns (Axis 1):", np.sum(arr_2d, axis=1))  # [6 15]
print("Overall Sum:", np.sum(arr_2d))  # 21 (sum of all elements)


# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr_3d)
print("Sum along depth (Axis 0):\n", np.sum(arr_3d, axis=0))  # 2D result
print("Sum along rows (Axis 1):\n", np.sum(arr_3d, axis=1))  # 2D result
print("Sum along columns (Axis 2):\n", np.sum(arr_3d, axis=2))  # 2D result


1D Array:
 [1 2 3 4]
Sum (Axis 0): 10

2D Array:
 [[1 2 3]
 [4 5 6]]
Sum along rows (Axis 0): [5 7 9]
Sum along columns (Axis 1): [ 6 15]
Overall Sum: 21

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Sum along depth (Axis 0):
 [[ 6  8]
 [10 12]]
Sum along rows (Axis 1):
 [[ 4  6]
 [12 14]]
Sum along columns (Axis 2):
 [[ 3  7]
 [11 15]]


In [2]:
print(arr_2d)
print(np.sum(arr_2d, axis=0))
print(arr_2d - np.sum(arr_2d, axis=0))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[[-4 -5 -6]
 [-1 -2 -3]]
