<a href="https://colab.research.google.com/github/mdrashidah/numpy-in-python/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mx = np.array([[1,1,2],[2,11,4],[23,32,12]], np.int8)
print(mx)
print(mx.shape)
print(type(mx))
print(mx.shape)
print(mx.dtype)
print(mx[[1,1]])


[[ 1  1  2]
 [ 2 11  4]
 [23 32 12]]
(3, 3)
<class 'numpy.ndarray'>
(3, 3)
int8
[[ 2 11  4]
 [ 2 11  4]]


In [ ]:
mx[0,1] = 100
print(mx)

[[  1 100   2]
 [  2  11   4]
 [ 23  32  12]]


***to check shape of the array***

In [ ]:
mx.shape  # to check the shape of the array
#mx.dtype  # to check the data type of the array

(3, 3)

In [ ]:
mx.size  # to check the size of the array

9

indexing in numpy arrays starts from 0

****DIFFERENT FUNCTIONS TO CREATE AN ARRAY IN NUMPY****

1. SETTING BIT SIZE IN ARRAY

In [ ]:
import numpy as np
ab = np.array([[32,12,23],[2,11,4],[23,32,12]], dtype = np.int64)
print(ab)
ab[1]

[[32 12 23]
 [ 2 11  4]
 [23 32 12]]


array([ 2, 11,  4])

In [ ]:
ab[1] = 100 # to change the value at index 1
print(ab)

[[ 32  12  23]
 [100 100 100]
 [ 23  32  12]]


***we typically use the following data types to increase or decrease the size of the array elements in the array:***

np.int8,
np.int16,
np.int32,
np.int64,
np.float16,
np.float32,
np.float64


*1. to check the size of the array*

In [ ]:
ab.size  #

9

*2. to check the number of dimensions of the array*

In [ ]:
ab.ndim

2

# **creation of array from other pyhton structures**

*1. to create a set of numbers*

In [ ]:
np.array({1,2,3,4})

array({1, 2, 3, 4}, dtype=object)

**2. for creation of zero(0) object array**

2.1) *by putting the array in int type*

In [ ]:
ze = np.zeros((3,5), dtype = np.int32)  # to create a zero(0) object array
print(ze)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


2.2) *represents the float number*

In [ ]:
ze = np.zeros((3,5))  # to create a zero(0) object array
print(ze)
ze.dtype

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


dtype('float64')

2.3) *to create range of a no.*

In [ ]:
display_range = np.arange(10)  # to create a range of numbers from 0 to 9
# It is as same as range in python in terms of functionality
print(display_range)

[0 1 2 3 4 5 6 7 8 9]


'arange' is a function to create an array with a given range.

2.4) *linear use  of line space in arrays*

(i) *normal type*

In [ ]:
lspace = np.linspace(0, 100, 10)  # to create a linearly spaced array
print(lspace)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


(ii) *if want to change the the data type of array*

In [ ]:
lspace2 = np.linspace(0, 100, 11, dtype=np.int64)
print(lspace2)

[  0  10  20  30  40  50  60  70  80  90 100]


2.5) *to create an empty array*

In [ ]:
emp = np.empty((2,2), dtype = int)
print(emp)

[[25895968444448860 23925768161198147]
 [32370111954616435 32370038941024348]]


2.6) *to create an empty array with the same shape and type as a given array*

In [ ]:
emp_like = np.empty_like(lspace2)
print(emp_like)

[  0  10  20  30  40  50  60  70  80  90 100]


2.7) *for identity matrices*

In [ ]:
idn_mtx = np.identity(5 ,dtype = np.int8)
print(idn_mtx)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


2.8) *for checking the shape of the array*


In [ ]:
idn_mtx.shape

(5, 5)

2.9) *reshaping of the array*

![WhatsApp Image 2025-09-04 at 09.36.59_d4fe205a.jpg](<attachment:WhatsApp Image 2025-09-04 at 09.36.59_d4fe205a.jpg>)

In [ ]:
import numpy as np
ab = np.arange(12)
print(ab)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
xy = ab.reshape(3,4)  # reshaping of the array
print(xy)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
xyz = xy.ravel()  # converting back to 1-D array
print(xyz)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


2.10) *transpose of a matrix*

In [ ]:
a2 = xy.T
print(a2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


2.11) *to get the iterator foR the array*

In [ ]:
a2.flat # to get the iterator for the array

![image.png](attachment:image.png)

***0x239ee7533b0 is the memory address of the variable 'a2'***

2.12) *to check the dimension of the array*

In [ ]:
a2.ndim

2

2.13) *size of the array*

In [ ]:
a2.size

12

2.14) *total bytes consumed by the array*

In [ ]:
a2.nbytes #

96

2.15) **to check max and min value of numpy array**

In [ ]:
one = np.array([12,3,234,32,12345])
print(one)

[   12     3   234    32 12345]


(i) *to get the index of the maximum value in the array*

In [ ]:
one.argmax()  #

np.int64(4)

*(ii) to get the index of the minimum value in the array*

In [ ]:
one.argmin()

np.int64(1)

2.16) *to sort the array*

In [ ]:
one.sort()  # to sort the array
print(one)  # display the sorted array

[    3    12    32   234 12345]


# 3)  NUMPY AXIS

![image.png](attachment:image.png)

![image.png](attachment:image.png)

![image.png](attachment:image.png)

--> example of 3d array:

![image.png](attachment:image.png)

In [ ]:
ar = np.array([
	[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]],
    [[25,26,27,28],[29,30,31,32],[33,34,35,36]]
])
print(ar) # 3-D array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [ ]:
ar2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ar2)  # 2-D array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ar.argmin()  # to get the index of the minimum value in the array

np.int64(0)

In [ ]:
ar2.max()  # to get the index of the maximum value in the array

np.int64(12)

In [ ]:
ar2.max(axis=0)  # to get the maximum value in each column

array([ 9, 10, 11, 12])

In [ ]:
ar2.max(axis=1) # to get the maximum value in each row

array([ 4,  8, 12])

In [ ]:
ar2.min(axis=0)  # to get the minimum value in each column

array([1, 2, 3, 4])

In [ ]:
sat = np.array([[9,8,10],[34,25,6],[7,80,79]])
print(sat)

[[ 9  8 10]
 [34 25  6]
 [ 7 80 79]]


In [ ]:
sat.argsort(axis = 1)  # to get the indices that would sort the array

array([[1, 0, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [ ]:
ar3 = np.array([[1,2,3],[5,6,8],[9,10,12]])
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ar3 + sat  # element-wise addition

array([[10, 10, 13],
       [39, 31, 14],
       [16, 90, 91]])

In [ ]:
ar3 - sat  # element-wise subtraction

array([[ -8,  -6,  -7],
       [-29, -19,   2],
       [  2, -70, -67]])

In [ ]:
ar3 * sat  # element-wise multiplication

array([[  9,  16,  30],
       [170, 150,  48],
       [ 63, 800, 948]])

In [ ]:
np.sqrt(ar3)  # to get the square root of each element in the array

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.82842712],
       [3.        , 3.16227766, 3.46410162]])

In [ ]:
ar3.sum()  # to get the sum of all elements in the array

np.int64(56)

In [ ]:
np.where(ar3 > 5)  # to get the indices of elements that satisfy the condition

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [ ]:
np.count_nonzero(ar3)  # to count the number of non-zero elements in the array

np.int64(9)

In [ ]:
np.nonzero(ar3) # returns the indices of non-zero elements in the input array

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))